---
- hosts: localhost
  tasks:    
    - name: get ec2 in my account
      ec2:
        region: us-east-2
        aws_access_key: "{{ lookup('env','id') }}"
        aws_secret_key: "{{ lookup('env','key') }}"
        state: stopped
        instance_ids:
          - i-07ad0a6755cf4e37d
          - i-0db033bafa6633bcf
          - i-001d6e72eb0f9afb5
      register: ec2_info

    - name: stoped instances suceessfully
      debug:
        var: ec2_info
      when: ec2_info is succeeded
