---
- hosts: localhost
  tasks:    
    - name: get ec2 in my account
      ec2_instance_info:
        aws_access_key: "{{ lookup('env','id') }}"
        aws_secret_key: "{{ lookup('env','key') }}"        
        region: us-east-2
      register: ec2_info    
        
    - set_fact:
        ec2_id: []
        
    - set_fact: 
        ec2_id: "{{ (ec2_info | json_query('instances[*].instance_id')) }}"
        
    - debug:
        var: ec2_id
        
    - name: Ensure tags are present on a resource
      ec2_tag:
        aws_access_key: "{{ lookup('env','id') }}"
        aws_secret_key: "{{ lookup('env','key') }}"
        region: us-east-2
        resource: "{{ item }}"
        state: present
        tags:          
          env: jenkins
          trigger: yes
      with_items: "{{ ec2_id }}"
